<a href="https://colab.research.google.com/github/Eduardoskei/rocketseat-challenge-meal_delivery_analysis/blob/main/meal_delivery_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importando libs e gerando DFs

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_orders = pd.read_csv("/content/pedidos.csv")
df_menu = pd.read_csv("/content/cardapio.csv")

## Análise Exploratória de Dados (EDA)

### Explorando df_orders

In [4]:
df_orders.head()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario
0,1,2023-11-16,222,Torta de Limao,23.0,12.93
1,2,2024-05-25,232,Esfiha,NaN,5.87
2,3,2024-12-20,276,Wrap de Frango,7.0,25.98
3,4,2024-10-17,198,Batata Frita,NaN,11.62
4,5,2023-07-06,385,Esfiha,17.0,6.94

In [5]:
df_orders.tail()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario
445,446,2024-02-27,360,Salada Caesar,30.0,27.35
446,447,2025-05-29,228,Salada Caesar,24.0,29.40
447,448,2025-08-23,243,Agua Mineral,26.0,4.54
448,449,2024-08-30,191,Pizza Calabresa,9.0,45.85
449,450,2025-09-29,122,Yakisoba,8.0,31.72

In [6]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       450 non-null    int64
 1   Data            450 non-null    object
 2   Cliente_ID      450 non-null    int64
 3   Item            450 non-null    object
 4   Quantidade      431 non-null    float64
 5   Preco_Unitario  430 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 21.2+ KB

In [7]:
df_orders.describe()

        ID_Pedido  Cliente_ID  Quantidade  Preco_Unitario
count  450.000000  450.000000  431.000000      430.000000
mean   225.500000  245.864444   15.902552       17.856581
std    130.048068   88.360604    9.087931       11.601652
min      1.000000  100.000000    1.000000        4.090000
25%    113.250000  169.000000    8.000000        8.920000
50%    225.500000  241.500000   16.000000       13.095000
75%    337.750000  325.750000   24.000000       27.402500
max    450.000000  399.000000   30.000000       46.070000

### Explorando df_menu

In [8]:
df_menu.head()

              Item  Categoria  Preco_Base
0       Hamburguer   Salgados        22.9
1     Batata Frita   Salgados        12.5
2  Pizza Mussarela   Salgados        39.9
3  Pizza Calabresa   Salgados        42.9
4    Salada Caesar  Saudaveis        28.0

In [9]:
df_menu.tail()

               Item Categoria  Preco_Base
15         Yakisoba  Oriental        29.9
16  Sorvete 2 bolas     Doces        10.9
17           Esfiha  Salgados         6.5
18           Pastel  Salgados         9.5
19         Empanada  Salgados         8.9

In [10]:
df_menu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Item        20 non-null     object
 1   Categoria   20 non-null     object
 2   Preco_Base  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [11]:
df_menu.describe()

       Preco_Base
count   20.000000
mean    17.570000
std     11.708211
min      4.500000
25%      8.900000
50%     12.700000
75%     26.875000
max     42.900000

##  Criação de Novas Colunas (Feature Engineering)

In [17]:
df_orders['Receita_Item'] = df_orders['Quantidade'] * df_orders['Preco_Unitario']

In [18]:
df_orders.head()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item
0,1,2023-11-16,222,Torta de Limao,23.0,12.93,297.39
1,2,2024-05-25,232,Esfiha,NaN,5.87,NaN
2,3,2024-12-20,276,Wrap de Frango,7.0,25.98,181.86
3,4,2024-10-17,198,Batata Frita,NaN,11.62,NaN
4,5,2023-07-06,385,Esfiha,17.0,6.94,117.98

## Tratamento de Valores Ausentes

In [26]:
# Identificando valores ausentes no df_orders
df_orders.isna().sum()

ID_Pedido          0
Data               0
Cliente_ID         0
Item               0
Quantidade        19
Preco_Unitario    20
Receita_Item      38
dtype: int64

In [27]:
# Identificando valores ausentes no df_menu
df_menu.isna().sum()

Item          0
Categoria     0
Preco_Base    0
dtype: int64

In [31]:
# Preenchendo valores ausentes na coluna Quantidade com a média
df_orders['Quantidade'].fillna(df_orders['Quantidade'].mean(), inplace=True)
df_orders.isna().sum()

/tmp/ipykernel_55327/3310150890.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_orders['Quantidade'].fillna(df_orders['Quantidade'].mean(), inplace=True)

ID_Pedido          0
Data               0
Cliente_ID         0
Item               0
Quantidade         0
Preco_Unitario    20
Receita_Item      38
dtype: int64

In [34]:
# Removendo linhas com valores nulos na coluna Preco_Unitario
df_orders.dropna(subset=['Preco_Unitario'], inplace=True)
df_orders.isna().sum()

ID_Pedido          0
Data               0
Cliente_ID         0
Item               0
Quantidade         0
Preco_Unitario     0
Receita_Item      18
dtype: int64

## Agregações por Item

In [37]:
df_grouped = df_orders.groupby('Item').agg({
    'Quantidade': 'sum',
    'Receita_Item': 'sum'
})

df_grouped

                     Quantidade  Receita_Item
Item
Acai 300ml           402.902552       6249.76
Agua Mineral         327.902552       1392.59
Batata Frita         323.902552       3785.57
Brownie              465.902552       4440.02
Cafe Expresso        392.000000       2657.71
Empanada             321.902552       2762.86
Esfiha               364.707657       2075.60
Hamburguer           510.805104      10859.02
Pastel               238.000000       2215.46
Pizza Calabresa      372.805104      14545.57
Pizza Mussarela      349.000000      14148.69
Refrigerante Lata    343.000000       2606.87
Salada Caesar        352.000000       9927.96
Smoothie de Morango  325.902552       4511.67
Sorvete 2 bolas      284.000000       3137.76
Suco de Laranja      263.805104       2116.74
Sushi 8 pecas        378.902552      11552.58
Torta de Limao       249.805104       2870.18
Wrap de Frango       248.000000       6611.08
Yakisoba             318.000000       9514.64

In [39]:
top_5_quantidade = df_grouped.sort_values(by='Quantidade', ascending=False)
top_5_quantidade.head()

               Quantidade  Receita_Item
Item
Hamburguer     510.805104      10859.02
Brownie        465.902552       4440.02
Acai 300ml     402.902552       6249.76
Cafe Expresso  392.000000       2657.71
Sushi 8 pecas  378.902552      11552.58

In [41]:
top_5_receita = df_grouped.sort_values(by='Receita_Item', ascending=False)
top_5_receita.head()

                 Quantidade  Receita_Item
Item
Pizza Calabresa  372.805104      14545.57
Pizza Mussarela  349.000000      14148.69
Sushi 8 pecas    378.902552      11552.58
Hamburguer       510.805104      10859.02
Salada Caesar    352.000000       9927.96

## Análise Temporal

In [47]:
df_orders['Data'] = pd.to_datetime(df_orders['Data'])

In [48]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 430 entries, 0 to 449
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       430 non-null    int64
 1   Data            430 non-null    datetime64[ns]
 2   Cliente_ID      430 non-null    int64
 3   Item            430 non-null    object
 4   Quantidade      430 non-null    float64
 5   Preco_Unitario  430 non-null    float64
 6   Receita_Item    412 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(1)
memory usage: 43.0+ KB

In [49]:
df_orders['Mes'] = df_orders['Data'].dt.month

In [51]:
receita_mensal = df_orders.groupby('Mes')['Receita_Item'].sum()
receita_mensal

Mes
1      9830.11
2     16011.54
3      7983.08
4      8296.86
5     11000.39
6      8084.72
7      9881.83
8     12691.00
9     14309.65
10     5143.68
11     6901.48
12     7847.99
Name: Receita_Item, dtype: float64

## Integração de Dados (Merge)

In [53]:
df_merged = pd.merge(df_orders, df_menu, on='Item', how='left')
df_merged.head()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item,Mes,Categoria,Preco_Base
0,1,2023-11-16,222,Torta de Limao,23.000000,12.93,297.39,11,Doces,12.9
1,2,2024-05-25,232,Esfiha,15.902552,5.87,NaN,5,Salgados,6.5
2,3,2024-12-20,276,Wrap de Frango,7.000000,25.98,181.86,12,Saudaveis,26.5
3,4,2024-10-17,198,Batata Frita,15.902552,11.62,NaN,10,Salgados,12.5
4,5,2023-07-06,385,Esfiha,17.000000,6.94,117.98,7,Salgados,6.5

In [54]:
receita_categoria = df_merged.groupby('Categoria')['Receita_Item'].sum()
receita_categoria

Categoria
Bebidas       8773.91
Doces        21209.39
Oriental     21067.22
Salgados     50392.77
Saudaveis    16539.04
Name: Receita_Item, dtype: float64

In [55]:
top_categoria = receita_categoria.sort_values(ascending=False)
top_categoria.head(1)

Categoria
Salgados    50392.77
Name: Receita_Item, dtype: float64

## Filtros e Consultas

In [62]:
filtered = df_merged[(df_merged['Categoria'] == 'Salgados') & (df_merged['Quantidade'] > 10)]

filtered

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item,Mes,Categoria,Preco_Base
1,2,2024-05-25,232,Esfiha,15.902552,5.87,NaN,5,Salgados,6.5
3,4,2024-10-17,198,Batata Frita,15.902552,11.62,NaN,10,Salgados,12.5
4,5,2023-07-06,385,Esfiha,17.000000,6.94,117.98,7,Salgados,6.5
5,6,2023-02-04,260,Empanada,16.000000,9.48,151.68,2,Salgados,8.9
14,15,2023-02-03,103,Batata Frita,14.000000,13.13,183.82,2,Salgados,12.5
...,...,...,...,...,...,...,...,...,...,...
404,423,2023-02-05,252,Pizza Calabresa,16.000000,41.75,668.00,2,Salgados,42.9
409,428,2023-07-11,278,Pastel,18.000000,9.30,167.40,7,Salgados,9.5
415,434,2024-07-17,249,Esfiha,26.000000,5.96,154.96,7,Salgados,6.5
422,442,2023-01-02,261,Esfiha,15.902552,6.83,NaN,1,Salgados,6.5
424,444,2024-04-16,133,Esfiha,27.000000,6.50,175.50,4,Salgados,6.5

## KPIs e Análise Estatística com NumPy

In [64]:
receita_total = np.sum(df_merged['Receita_Item'])
receita_total

np.float64(117982.33000000002)

In [65]:
total_itens = np.sum(df_merged['Quantidade'])
total_itens

np.float64(6833.245939675175)

In [67]:
num_pedidos = df_merged['ID_Pedido'].nunique()
ticket_medio = receita_total / num_pedidos
ticket_medio

np.float64(274.37751162790704)